fix: config watcher follow symlinks
rathole-org/rathole pull request #361
Opened 2024-05-10 11:49 UTC by Bubbleioa

https://github.com/rapiz1/rathole/issues/359

2025-06-17 16:16 UTC, yujqiao commented
This one I'm a bit hesitated. If the config is `/etc/rathole.toml`, this will result in watching every file change under /etc

2025-06-17 16:18 UTC, yujqiao commented
That said, I cannot think of another way to fix symlink. `readlink -f` probably will fail when the file is edited by vim because the inode number could change. Can we watch recursively only when the target file is a symlink? so we can limit the impact

2025-06-17 16:19 UTC, yujqiao requested changes
i don't think the current approach can be merged given comments above

2026-08-22 18:02 UTC, fernvenue commented
Thanks for working on symlink support in the config watcher.

Back in June 2025 there was a concern raised about the approach: `readlink -f` style resolution can break when a file is edited by tools like vim, since the inode number can change underneath it. That concern was never addressed.

Since it's been over a year with no response, I'm closing this for now. Feel free to open a new pull request against `dev` if you'd like to tackle the symlink case differently.

2026-08-22 18:02 UTC, closed without merging